version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.16
executors:
  build:
    docker:
      - image: cimg/base:2023.04

workflows:
  ci-cd:
    jobs:

      - gcp-gcr/build-and-push-image:
          name: Build Image
          executor: build
          extra_build_args: '--label org.opencontainers.image.source=https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME --label org.opencontainers.image.revision=$CIRCLE_SHA1'
          context: gcp-oidc-artifact-registry
          dockerfile: Dockerfile
          registry-url: europe-west1-docker.pkg.dev
          use_oidc: true
          image: docker/certspotter
          tag: ${CIRCLE_SHA1}
          # https://circleci.com/docs/2.0/building-docker-images/#docker-version
          remote-docker-version: default
          setup-remote-docker: true
          use-docker-layer-caching: true
